# Generated by Django 4.2.27 on 2026-02-13 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team2', '0005_userdetails_created_at_userdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('score', models.IntegerField(help_text='Score from 1 to 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='team2.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', 'user_id'], name='team2_ratin_lesson__c8e0d5_idx'), models.Index(fields=['lesson', 'score'], name='team2_ratin_lesson__cce654_idx')],
                'unique_together': {('lesson', 'user_id')},
            },
        ),
    ]
