# Generated by Django 4.2.27 on 2026-02-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team2', '0005_userdetails_created_at_userdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='معلمی که این کلاس را ساخته است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to='team2.userdetails'),
        ),
    ]
