# Generated by Django 4.2.27 on 2026-02-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team2', '0006_lesson_teacher_id_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('question_text', models.TextField(help_text='متن سؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='team2.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('watch_duration_seconds', models.IntegerField(default=0, help_text='مدت زمان تماشای ویدیو به ثانیه')),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False, help_text='آیا کاربر ویدیو را کامل دیده است')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='team2.lesson')),
            ],
            options={
                'ordering': ['-view_date'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('answer_text', models.TextField(help_text='متن پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='team2.question')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['lesson', 'user_id'], name='team2_quest_lesson__2a66a5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['lesson', '-created_at'], name='team2_quest_lesson__6646de_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonview',
            index=models.Index(fields=['lesson', 'user_id'], name='team2_lesso_lesson__69dcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonview',
            index=models.Index(fields=['lesson', '-view_date'], name='team2_lesso_lesson__22bcca_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonview',
            index=models.Index(fields=['user_id', '-view_date'], name='team2_lesso_user_id_feee9a_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'user_id'], name='team2_answe_questio_4d8a10_idx'),
        ),
    ]
