# Generated by Django 5.2.11 on 2026-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team9', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='current_day',
            field=models.IntegerField(default=0),
        ),
    ]
