# Generated by Django 5.2.11 on 2026-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team9', '0002_alter_word_current_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
