# Generated by Django 5.2.11 on 2026-02-09 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team9', '0003_word_next_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='next_review_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
