# Generated by Django 6.0.2 on 2026-02-03 15:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grammar_score', models.FloatField(blank=True, null=True)),
                ('vocabulary_score', models.FloatField(blank=True, null=True)),
                ('coherence_score', models.FloatField(blank=True, null=True)),
                ('fluency_score', models.FloatField(blank=True, null=True)),
                ('pronunciation_score', models.FloatField(blank=True, null=True)),
                ('feedback_summary', models.TextField(blank=True)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('submission_type', models.CharField(choices=[('writing', 'Writing'), ('listening', 'Listening')], max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningSubmission',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='listening_details', serialize=False, to='team11.submission')),
                ('topic', models.CharField(max_length=500)),
                ('audio_file_url', models.CharField(max_length=500)),
                ('duration_seconds', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='writing_details', serialize=False, to='team11.submission')),
                ('topic', models.CharField(max_length=500)),
                ('text_body', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-created_at', 'user_id'], name='team11_subm_created_6f1cff_idx'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_result', to='team11.submission'),
        ),
    ]
